# Generated by Django 2.1.15 on 2020-03-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
