# Generated by Django 2.1.15 on 2020-03-10 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200306_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='api.Event'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='api.Event'),
        ),
    ]
