# Generated by Django 2.1.15 on 2020-03-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200316_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='event_q',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_id', to='api.Event'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='event_s',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_id', to='api.Event'),
        ),
    ]
