# Generated by Django 2.1.15 on 2020-03-19 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireans',
            old_name='person',
            new_name='candidate',
        ),
        migrations.AddField(
            model_name='questionnaireans',
            name='evaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaireAns_e', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionnaireans',
            name='Answer',
            field=models.IntegerField(),
        ),
    ]
