# Generated by Django 2.1.15 on 2020-03-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200319_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Text',
            new_name='text',
        ),
    ]
