# Generated by Django 2.1.15 on 2020-03-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200319_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionnaires',
            field=models.ManyToManyField(related_name='questions', to='api.Questionnaire'),
        ),
    ]
