# Generated by Django 2.1.15 on 2020-03-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200319_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireans',
            old_name='Answer',
            new_name='answer',
        ),
    ]
