# Generated by Django 2.1.15 on 2020-03-19 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200319_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireans',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionnaireans',
            name='evaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaireAns_e', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionnaireans',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Questionnaire'),
        ),
    ]
