# Generated by Django 2.1.15 on 2020-03-19 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200319_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireans',
            name='answer',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
    ]
