# Generated by Django 2.1.15 on 2020-03-19 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200319_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionnaireans',
            unique_together={('candidate', 'question')},
        ),
    ]
