# Generated by Django 2.1.15 on 2020-03-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200329_1622'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('event', 'evaluator')},
        ),
    ]
