# Generated by Django 2.1.15 on 2020-03-30 22:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200330_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='resume',
            field=models.FileField(upload_to='', verbose_name=api.models.Resume),
        ),
    ]
