# Generated by Django 2.1.15 on 2020-03-30 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200330_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Resume'),
        ),
    ]
