# Generated by Django 2.1.15 on 2020-03-30 23:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200330_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name=api.models.Resume),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
