# Generated by Django 2.1.15 on 2020-03-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200330_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='file',
            new_name='resume_file',
        ),
        migrations.AlterField(
            model_name='registered',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Resume'),
        ),
    ]
