# Generated by Django 2.1.15 on 2020-03-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200330_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_file',
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
