# Generated by Django 2.1.15 on 2020-04-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200331_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
    ]
