# Generated by Django 2.1.15 on 2020-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='Unnamed Group', max_length=50),
            preserve_default=False,
        ),
    ]
