# Generated by Django 2.1.15 on 2020-04-14 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionnaires',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='event_q',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='event_s',
        ),
        migrations.AddField(
            model_name='event',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_q', to='api.Questionnaire'),
        ),
        migrations.AddField(
            model_name='event',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_s', to='api.Questionnaire'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.Questionnaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_survey',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questionnaireans',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question'),
        ),
    ]
