# Generated by Django 2.1.15 on 2020-04-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200413_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(default='Unnamed Questionnaire', max_length=50),
            preserve_default=False,
        ),
    ]
