# Generated by Django 2.1.15 on 2020-04-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_questionnaire_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Description',
            field=models.CharField(max_length=100000),
        ),
    ]
